name: Assign reviewer
on:
  pull_request:
  pull_request_review:
jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: CHECK PR FOR LOCKS
        id: diff_check
        run: |
          DIFF=$(git --no-pager diff origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} -U1 | { grep 🔒 || true; })
          if [ "$DIFF" != "" ]
          then
          echo "Special review required"
          echo '::set-output name=LOCKED_LINES_PRESENT::1'
          else
          echo '::set-output name=LOCKED_LINES_PRESENT::0'
          fi
          # echo "####################### GET LIST OF REVIEWERS #######################################"
          # USERS_REVIEW_REQUESTED_FROM=$(cat $GITHUB_EVENT_PATH | jq '.pull_request.requested_reviewers | map("@" + .login) | join(" ")')
          # echo "Reviewers: $USERS_REVIEW_REQUESTED_FROM"
          # echo "##############################################################"
          # echo "FINISH"
          # cat $GITHUB_EVENT_PATH | jq
          # echo "##############################################################"
          # echo ${{ github.event.review.user.login }}
      - name: assign reviewer
        if: steps.diff_check.outputs.LOCKED_LINES_PRESENT == 1
        uses: LongOddCode/assign-reviewer@0.2.2
        with:
          #github access token.
          token: ${{ secrets.GITHUB_TOKEN }}
          script: bash
          reviewers: '["sergioko747", "sergioko757"]'
          result: LOCKED_LINES_PRESENT
          run: |
            echo "1"
            echo ${{ steps.diff_check.outputs.LOCKED_LINES_PRESENT }}


