name: changes
on: push
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        name: File changes
        uses: trilom/file-changes-action@v1.2.3
      - name: Printenv
        run: |
          echo ${{ steps.file_changes_outputs_files }}
          echo ${{ steps.file_changes.outputs.files_modified }}
          echo ${{ steps.file_changes.outputs.files_added }}
          echo ${{ steps.file_changes.outputs.files_removed }}
          # printenv
          cat $GITHUB_EVENT_PATH | jq
