name: Test action
on:
  pull_request:
  pull_request_review:
jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Print a greeting
        run: |
          # ls
          # echo "###### PRINTENV ############"
          # printenv
          # git status
          # git branch -a
          #git log --oneline
          echo "github.event.pull_request.head.ref"
          echo ${{ github.event.pull_request.head.ref }}
          echo "github.event.pull_request.base.ref"
          echo ${{ github.event.pull_request.base.ref }}
          # echo ${{ github.event.pull_request.requested_reviewers }}
          echo "SHOW ACTUAL DIFF"
          git --no-pager diff origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} -U1
          echo "SHOW FILTERED DIFF"
          git --no-pager diff origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} -U1 -G 🔒
          echo "Check whether diff contain locks"
          DIFF=$(git --no-pager diff origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} -U1 -G 🔒)
          if [ "$DIFF" != "" ]
          then
          echo "Special review required"
          fi
          echo "FINISH"

