name: Test action
on:
  pull_request:
  pull_request_review:
jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: CHECK PR FOR LOCKS
        run: |
          DIFF=$(git --no-pager diff origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} -U1 | grep 🔒)
          if [ "$DIFF" != "" ]
          then
          echo "Special review required"
          fi
          echo "####################### GET LIST OF REVIEWERS #######################################"
          USERS_REVIEW_REQUESTED_FROM=$(cat $GITHUB_EVENT_PATH | jq '.pull_request.requested_reviewers | map("@" + .login) | join(" ")')
          echo "Reviewers: $USERS_REVIEW_REQUESTED_FROM"
          echo "##############################################################"
          echo "FINISH"
          cat $GITHUB_EVENT_PATH | jq
          echo "##############################################################"
          echo ${{ github.event.pull_request }}

