name: 'PR Gatekeeper'

on:
  pull_request:
    # types:
    #   [
    #     assigned,
    #     unassigned,
    #     opened,
    #     reopened,
    #     synchronize,
    #     review_requested,
    #     review_request_removed
    #   ]
  pull_request_review:

jobs:
  pr-gatekeeper:
    name: PR Gatekeeper
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: show dir
        run: |
          ls -aR
      - name: pr-gatekeeper
        uses: ./.github/actions/pr-gatekeeper
        # uses: sergioko737/rust_book/.github/actions/pr-gatekeeper@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}